config/routes.rb
Rails.application.routes.draw do
  root to: 'responses#index'
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  get '/.well-known/acme-challenge/:id' => 'application#letsencrypt'

  resources :responses

  resources :admin, only: [:index, :destroy] do
    member do
      post 'pair'
    end
  end

  post 'hook', controller: 'webhook'
end

app/views/admin/index.html.erb
<% content_for(:title) { @title } %>
<div style='padding-bottom: 20px;' class='row'>
  <div class="col-md-2">
    <h3>Stats</h3>
  </div>
  <div class="col-md-2">
    <h3>Paired: <%= User.completed.paired.count('*') %></h3>
  </div>
  <div class="col-md-2">
    <h3>Single: <%= User.completed.unpaired.count('*') %></h3>
  </div>
  <div class="col-md-2">
    <h3>Opens: <%= Pairing.where(status: [:opened, :clicked]).count %></h3>
  </div>
  <div class="col-md-2">
    <h3>Clicks: <%= Pairing.where(status: :clicked).count %></h3>
  </div>
  <div class="col-md-2">
    <h3>SB Codes: <%= GiftCard.where(store: "Starbucks", pairing: nil).count %></h3>
  </div>
</div>

<div style='padding-bottom: 20px;' class='row'>
  <div class="col-md-4">
    <p><h1><%= @title %></h1></p>
  </div>
  <div class="col-md-8 text-right">
    <form class="form-inline" style="padding-top: 25px;">
      <input type="text" class="form-control" placeholder="Name or email" name="name_email" value="<%= params[:name_email] %>">
      <input type="text" class="form-control" placeholder="ZIP code" name="zip" value="<%= params[:zip] %>" style="width:6em" maxlength="5" >
      <div class="input-group">
        <span class="input-group-addon">Supported</span>
        <%= select_tag(:supported, '<option value="">Any</option>'.html_safe +
                       options_for_select(Hash[User.supporteds.collect {|k, v| [k.capitalize, v] }], params[:supported]),
                       class: "form-control") %>
      </div>
      <input type="hidden" name="paired" value="<%= params[:paired] %>">
      <button class="btn btn-default" type="submit">Search</button>
    </form>
  </div>
</div>

<div>
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
        <td>Name</td>
        <td>Email</td>
        <td>Created</td>
        <td>Zip</td>
        <td>Supported</td>
        <td>Desired</td>
        <td>Starbucks</td>
        <% if @paired %>
          <td>Status</td>
        <% else %>
          <td>Remove</td>
        <% end %>
      </tr>
    </thead>
    <tbody>
      <% @users.each do |user| %>
        <tr title="<%= user.background %>" data-toggle="modal" data-target="#modal_<%= user.id %>" class="clickable">
          <td><%= user.name %></td>
          <td><%= user.email %></td>
          <td><%= user.created_at.to_s(:short) %></td>
          <td><%= user.zip %></td>
          <td><%= user.supported.titleize %></td>
          <td><%= user.desired.titleize %></td>
          <td><%= user.nearest_starbucks.present? ? "&#10003;".html_safe : "&#10007;".html_safe %></td>
          <% if @paired %>
            <td><%= user.pairings.last.status %></td>
          <% else %>
            <td class="text-center">
              <a class="btn btn-danger btn-xs" data-method="delete" href="<%= admin_path(user) %>" data-remote="true">
                &#10007;
              </a>
            </td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>

  <nav>
    <ul class="pager" style="padding-top: 10px;">
      <% if @page > 0 %>
        <li><a href="<%= admin_index_path(paired: @paired, page: @page - 1) %>">Previous</a></li>
      <% end %>
      <% if @page < @pages - 1 %>
        <li><a href="<%= admin_index_path(paired: @paired, page: @page + 1) %>">Next</a></li>
      <% end %>
    </ul>
    <ul class="pager" style="margin-top: -10px;">
      <li>
        <a href="<%= admin_index_path(paired: !@paired) %>">
         <%= @paired ? 'Unpaired' : 'Paired'%> Users
        </a>
      </li>
    </ul>
  </nav>
</div>

<% @users.each do |user| %>
  <div class="modal fade" tabindex="-1" role="dialog" id="modal_<%= user.id %>">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <h3 class="modal-title"><%= user.name %></h3>
        </div>
        <div class="modal-body">
          <p>
            A <%= user.supported_nice %> supporter who wants to talk to someone who supported <%= user.desired.titleize %>.
            <% if user.zip.present? %>
              He or she lives at zip code <%= user.zip %>.
            <% end %>
          </p>
          <h4>Background</h4>
          <p><%= user.background %></p>
          <% %w(info geolocation ip).each do |attr| %>
            <% if user.send(attr).present? %>
              <h4><%= attr.titleize %></h4>
              <p><pre><%= user.send(attr).to_json %></pre></p>
            <% end %>
          <% end %>
          <% if user.paired_users.present? %>
            <hr>
            <% user.paired_users.each_with_index do |paired_user, i| %>
              <h4>Pairing (<%= paired_user.first_name %>)</h4>
              <p><%= user.first_name %> is paired with <%= paired_user.name %>, a <%= paired_user.supported_nice %> supporter<% if paired_user.zip.present? %> from <%= paired_user.zip %><% end %>. Their email is <%= paired_user.email %>.</p>
              <p><%= paired_user.background %></p>
              <p>The status of this email is <b><%= user.pairings[i].status %></b>.</p>
            <% end %>
          <% elsif user.possible_pairing.present? %>
            <h4>Suggested Pairing</h4>
            <p>We suggest pairing <%= user.first_name %> with <%= user.possible_pairing.name %>, a <%= user.possible_pairing.supported_nice %> supporter<% if user.possible_pairing.zip.present? %> who lives at <%= user.possible_pairing.zip %><% end %>. This pairing <b>is<%= ' not' unless Pairing.pair(user, user.possible_pairing).same_city? %></b> eligible for a Starbucks code.</p>
            <p><%= user.possible_pairing.background %></p>
          <% end %>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          <% if user.paired_users.present? %>
            <% user.paired_users.each do |paired_user| %>
              <a class="btn btn-primary" href="mailto:<%= user.email %>,<%= paired_user.email %>?subject=<%=h "Hi From The Other Side" %>">Email (<%= paired_user.first_name %>)</a>
            <% end %>
          <% elsif user.possible_pairing.present? %>
            <a class="btn btn-primary" href="<%= pair_admin_path(user.id) %>" data-method="post" data-remote="true">Pair</a>
          <% end %>
        </div>
      </div>
    </div>
  </div>
<% end %>